version: '3.8'

networks:
  serving_prod_net:

services:
  serving-api:
    container_name: serving-api
    build:
      context: ./serving
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - serving_prod_net

  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - API_URL=http://serving-api:8080/
    ports:
      - "8081:8081"
    networks:
      - serving_prod_net
