version: '3.8'

networks:
  serving_prod_net:
    external: true

services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - API_URL=http://serving-api:8080/
    networks:
      - serving_prod_net
